INSERT INTO spelllist (spellid, classid, subclassid, spelllevel, classlevel) VALUES 
((SELECT spellid from spell WHERE name = 'Acid Splash'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Acid Splash'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Blade Ward'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Blade Ward'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Blade Ward'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Blade Ward'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Chill Touch'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Chill Touch'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Chill Touch'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Dancing Lights'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Dancing Lights'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Dancing Lights'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Druidcraft'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Eldritch Blast'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Fire Bolt'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Fire Bolt'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Friends'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Friends'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Friends'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Friends'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Guidance'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Guidance'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Light'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Light'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Light'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Light'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Mage Hand'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Mage Hand'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Mage Hand'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Mage Hand'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Mending'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Mending'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Mending'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Mending'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Mending'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Message'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Message'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Message'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Minor Illusion'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Minor Illusion'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Minor Illusion'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Minor Illusion'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Poison Spray'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Poison Spray'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Poison Spray'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Poison Spray'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Prestidigitation'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Prestidigitation'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Prestidigitation'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Prestidigitation'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Produce Flame'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Ray of Frost'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Ray of Frost'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Resistance'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Resistance'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Sacred Flame'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Shillelagh'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Shocking Grasp'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Shocking Grasp'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Spare the Dying'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Thaumaturgy'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Thorn Whip'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'True Strike'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'True Strike'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'True Strike'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'True Strike'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Vicious Mockery'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 0, 1),
((SELECT spellid from spell WHERE name = 'Alarm'), (SELECT classid FROM class WHERE name = 'Ranger'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Alarm'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Animal Friendship'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Animal Friendship'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Animal Friendship'), (SELECT classid FROM class WHERE name = 'Ranger'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Armor of Agathys'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Arms of Hadar'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Bane'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Bane'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Bless'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Bless'), (SELECT classid FROM class WHERE name = 'Paladin'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Burning Hands'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Burning Hands'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Charm Person'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Charm Person'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Charm Person'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Charm Person'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Charm Person'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Chromatic Orb'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Chromatic Orb'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Color Spray'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Color Spray'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Command'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Command'), (SELECT classid FROM class WHERE name = 'Paladin'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Compelled Duel'), (SELECT classid FROM class WHERE name = 'Paladin'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Comprehend Languages'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Comprehend Languages'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Comprehend Languages'), (SELECT classid FROM class WHERE name = 'Warlock'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Comprehend Languages'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Create Or Destroy Water'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Create Or Destroy Water'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Cure Wounds'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Cure Wounds'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Cure Wounds'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Cure Wounds'), (SELECT classid FROM class WHERE name = 'Paladin'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Cure Wounds'), (SELECT classid FROM class WHERE name = 'Ranger'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Evil and Good'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Evil and Good'), (SELECT classid FROM class WHERE name = 'Paladin'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Magic'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Magic'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Magic'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Magic'), (SELECT classid FROM class WHERE name = 'Paladin'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Magic'), (SELECT classid FROM class WHERE name = 'Ranger'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Magic'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Magic'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Poison and Disease'), (SELECT classid FROM class WHERE name = 'Cleric'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Poison and Disease'), (SELECT classid FROM class WHERE name = 'Druid'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Poison and Disease'), (SELECT classid FROM class WHERE name = 'Paladin'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Detect Poison and Disease'), (SELECT classid FROM class WHERE name = 'Ranger'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Disguise Self'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Disguise Self'), (SELECT classid FROM class WHERE name = 'Sorcerer'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Disguise Self'), (SELECT classid FROM class WHERE name = 'Wizard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Dissonant Whispers'), (SELECT classid FROM class WHERE name = 'Bard'), NULL, 1, 1),
((SELECT spellid from spell WHERE name = 'Divine Favor'), (SELECT classid FROM class WHERE name = 'Paladin'), NULL, 1, 1),








