--String to add:  , 0, 0, 'Save DC','Acid', (SELECT diceid FROM dice WHERE sides = 6), 1, 'None'

INSERT INTO spell (name, school, casttime, spellrange, duration, components, description, saveability, hitdcdie, hitdcdicenum, hitdcmod, effecttypeid, effectdicetype, effectdicenum, effectmod, levelmod, levelmodtype) VALUES
('Acid Splash', 'Conjuration', '1 Action', '60 Feet', 'Instantaneous', 'V, S', 'You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage. ', (SELECT abilityid FROM ability WHERE abbrev = 'Dex'), NULL, 0, 'Save DC', (SELECT effecttypeid FROM effecttype WHERE name = 'Acid'), (SELECT diceid FROM dice WHERE sides = 6), 1, 'None', 0, 'None'),
('Blade Ward', 'Abjuration', '1 Action', 'Self', '1 round', 'V, S', 'You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Chill Touch', 'Necromancy', '1 Action', '120 feet', '1 round', 'V, S', 'You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can’t regain hit points until the start of your next turn. Until then, the hand clings to the target. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.', NULL, (SELECT diceid FROM dice WHERE sides = 20), 1, 'Spell Attack', (SELECT effecttypeid FROM effecttype WHERE name = 'Necrotic'), (SELECT diceid FROM dice WHERE sides = 8), 1, 'None', 0, 'None'),
('Dancing Lights', 'Evocation', '1 Action', '120 feet', 'Concentration up to 1 minute', 'V, S, M', 'You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can also combine the four lights into one glowing vaguely humanoid form of Medium size. Whichever form you choose, each light sheds dim light in a 10-foot radius. As a bonus action on your turn, you can move the lights up to 60 feet to a new spot within range. A light must be within 20 feet of another light created by this spell, and a light winks out if it exceeds the spell’s range. ', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Druidcraft', 'Transmutation', '1 Action', '30 Feet', 'Instantaneous', 'V, S', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Eldritch Blast', 'Evocation', '1 Action', '120 Feet', 'Instantaneous', 'V, S', 'Add description here', NULL, (SELECT diceid FROM dice WHERE sides = 20), 1, 'Spell Attack', (SELECT effecttypeid FROM effecttype WHERE name = 'Force'), (SELECT diceid FROM dice WHERE sides = 10), 1, 'None', 0, 'None'),
('Fire Bolt', 'Evocation', '1 Action', '120 feet', 'Instantaneous', 'V, S', 'Add description here', NULL, (SELECT diceid FROM dice WHERE sides = 20), 1, 'Spell Attack', (SELECT effecttypeid FROM effecttype WHERE name = 'Fire'), (SELECT diceid FROM dice WHERE sides = 10), 1, 'None', 0, 'None'),
('Friends', 'Enchantment', '1 Action', 'Self', 'Concentration, up to 1 minute', 'S, M', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Guidance', 'Divination', '1 Action', 'Touch', 'Concentration up to 1 minute', 'V, S', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Light', 'Evocation', '1 Action', 'Touch', '1 hour', 'V, M', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Mage Hand', 'Conjuration', '1 Action', '30 feet', '1 minute', 'V, S', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Mending', 'Transmutation', '1 Minute', 'Touch', 'Instantaneous', 'V, S, M', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Message', 'Transmutation', '1 Action', '120 feet', '1 round', 'V, S, M', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Minor Illusion', 'Illusion', '1 Action', '30 feet', '1 minute', 'S, M', 'Add description here', (SELECT abilityid FROM ability WHERE abbrev = 'Int') ,NULL, 0, 'Save DC', NULL, NULL, 0, 'None', 0, 'None'),
('Poison Spray', 'Conjuration', '1 Action', '10 feet', 'Instantaneous', 'V, S', 'Add description here', (SELECT abilityid FROM ability WHERE abbrev = 'Con'), NULL, 0, 'Save DC', (SELECT effecttypeid FROM effecttype WHERE name = 'Poison'), (SELECT diceid from dice WHERE sides = 12), 1, 'None', 0, 'None' ),
('Prestidigitation', 'Transmutation', '1 Action', '10 feet', 'Up to 1 hour', 'V, S', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Produce Flame', 'Conjuration', '1 Action', 'Self', '10 minutes', 'V, S', 'Add description here', NULL, (SELECT diceid FROM dice WHERE sides = 20), 1, 'Spell Attack', (SELECT effecttypeid FROM effecttype WHERE name = 'Fire'), (SELECT diceid FROM dice WHERE sides = 8), 1, 'None', 0, 'None'),
('Ray of Frost', 'Evocation', '1 Action', '60 feet', 'Instantaneous', 'V, S', 'Add description here', NULL, (SELECT diceid FROM dice WHERE sides = 20), 1, 'Spell Attack', (SELECT effecttypeid FROM effecttype WHERE name = 'Frost'), (SELECT diceid FROM dice WHERE sides = 8), 1, 'None', 0, 'None'),
('Resistance', 'Abjuration', '1 Action', 'Touch', 'Concentration up to 1 minute', 'V, S, M', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Sacred Flame', 'Evocation', '1 Action', '60 feet', 'Instantaneous', 'V, S', 'Add description here', (SELECT abilityid FROM ability WHERE abbrev = 'Dex'), NULL, 0, 'Save DC', (SELECT effecttypeid FROM effecttype WHERE name = 'Radiant'), (SELECT diceid FROM dice WHERE sides = 8), 1, 'None', 0, 'None'),
--('Shillelagh', 'Transmutation', '1 Bonus Action', 'Touch', '1 minute', 'V, S, M', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
--('Shocking Grasp', 'Evocation', '1 Action', 'Touch', 'Instantaneous', 'V, S', 'Add description here'),
('Spare the Dying', 'Necromancy', '1 Action', 'Touch', 'Instantaneous', 'V, S', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Thaumaturgy', 'Transmutation', '1 Action', '30 feet', 'Up to 1 minute', 'V', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Thorn Whip', 'Transmutation', '1 Action', '30 feet', 'Instantaneous', 'V, S, M', 'Add description here', NULL, (SELECT diceid FROM dice WHERE sides = 20), 1, 'Spell Attack', (SELECT effecttypeid FROM effecttype WHERE name = 'Piercing'), (SELECT diceid FROM dice WHERE sides = 6), 1, 'None', 0, 'None'),
('True Strike', 'Divination', '1 Action', '30 feet', 'Concentration up to 1 round', 'S', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Vicious Mockery', 'Enchantment', '1 Action', '60 feet', 'Instantaneous', 'V', 'Add description here', NULL, NULL, 0, 'Save DC', (SELECT effecttypeid FROM effecttype WHERE name = 'Psychic'), (SELECT diceid FROM dice WHERE sides = 4), 1, 'None', 0, 'None'),
('Alarm', 'Abjuration', '1 Minute R', '30 feet', '8 Hours', 'V, S, M' , 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Animal Friendship', 'Enchantment', '1 Action', '30 feet', '24 hours', 'V, S, M', 'Add description here', (SELECT abilityid FROM ability WHERE abbrev = 'Wis'), NULL, 0, 'Save DC', (SELECT effecttypeid FROM effecttype WHERE name = 'Charm'), NULL, 0, 'None', 0, 'None'),
('Armor of Agathys', 'Abjuration', '1 Action', 'Self', '1 hour', 'V, S, M', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Arms of Hadar', 'Conjuration', '1 Action', 'Self (10-foot radius)', 'Instantaneous', 'V, S', 'Add description here', NULL, NULL, 0, 'Save DC', (SELECT effecttypeid FROM effecttype WHERE name = 'Necrotic'), (SELECT diceid FROM dice WHERE sides = 6), 2, 'None', 1, 'EffectDieNum'),
('Bane', 'Enchantment', '1 Action', '30 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here', (SELECT abilityid FROM ability WHERE abbrev = 'Dex'), NULL, 0, 'Save DC', (SELECT effecttypeid FROM effecttype WHERE name = 'Bane'), NULL, 0, 'None', 0, 'None'),
('Bless', 'Enchantment', '1 Action', '30 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here', NULL, NULL, 0, 'None', NULL, NULL, 0, 'None', 0, 'None'),
('Burning Hands', 'Evocation', '1 Action', 'Self (15-foot cone)', 'Instantaneous', 'V, S', 'Add description here', (SELECT abilityid FROM ability WHERE abbrev = 'Cha'), NULL, 0, 'Save DC', (SELECT effecttypeid FROM effecttype WHERE name = 'Fire'), (SELECT diceid FROM dice WHERE sides = 6), 3, 'None', 1, 'EffectDieNum'),
('Charm Person', 'Enchantment', '1 Action', '30 feet', '1 hour', 'V, S', 'Add description here', (SELECT abilityid FROM ability WHERE abbrev = 'Wis'), NULL, 0, 'Save DC', (SELECT effecttypeid FROM effecttype WHERE name = 'Charm'), NULL, 0, 'None', 0, 'None'),
--('Chromatic Orb', 'Evocation', '1 Action', '90 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Color Spray', 'Illusion', '1 Action', 'Self (15-foot cone)', '1 round', 'V, S, M', 'Add description here'),
('Command', 'Enchantment', '1 Action', '60 feet', '1 round', 'V', 'Add description here'),
('Compelled Duel', 'Enchantment', '1 Bonus Action', '30 feet', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Comprehend Languages', 'Divination', '1 Action R', 'Self', '1 hour', 'V, S, M', 'Add description here'),
('Create or Destroy Water', 'Transmutation', '1 Action', '30 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Cure Wounds', 'Evocation', '1 Action', 'Touch', 'Instantaneous', 'V, S', 'Add description here'),
('Detect Evil and Good', 'Divination', '1 Action', 'Self', 'Concentration, up to 10 minutes', 'V, S', 'Add description here'),
('Detect Magic', 'Divination', '1 Action R', 'Self', 'Concentration, up to 10 minutes', 'V, S', 'Add description here'),
('Detect Poison and Disease', 'Divination', '1 Action R', 'Self', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Disguise Self', 'Illusion', '1 Action', 'Self', '1 hour', 'V, S', 'Add description here'),
('Dissonant Whispers', 'Enchantment', '1 Action', '60 feet', 'Instantaneous', 'V', 'Add description here'),
('Divine Favor', 'Evocation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Ensnaring Strike', 'Conjuration', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Entangle', 'Conjuration', '1 Action', '90 feet', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Expeditious Retreat', 'Transmutation', '1 Bonus Action', 'Self', 'Concentration, up to 10 minutes', 'V, S', 'Add description here'),
('Faerie Fire', 'Evocation', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('False Life', 'Necromancy', '1 Action', 'Self', '1 hour', 'V, S, M', 'Add description here'),
('Feather Fall', 'Transmutation', '1 Reaction', '60 feet', '1 minute', 'V, M', 'Add description here'),
('Find Familiar', 'Conjuration', '1 Hour R', '10 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Fog Cloud', 'Conjuration', '1 Action', '120 feet', 'Concentration, up to 1 hour', 'V, S', 'Add description here'),
('Goodberry', 'Transmutation', '1 Action', 'Touch', 'Instantaneous', 'V, S, M', 'Add description here'),
('Grease', 'Conjuration', '1 Action', '60 feet', '1 minute', 'V, S, M', 'Add description here'),
('Guiding Bolt', 'Evocation', '1 Action', '120 feet', '1 round', 'V, S', 'Add description here'),
('Hail of Thorns', 'Conjuration', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Healing Word', 'Evocation', '1 Bonus Action', '60 feet', 'Instantaneous', 'V', 'Add description here'),
('Hellish Rebuke', 'Evocation', '1 Reaction', '60 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Heroism', 'Enchantment', '1 Action', 'Touch', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Hex', 'Enchantment', '1 Bonus Action', '90 feet', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Hunters Mark', 'Divination', '1 Bonus Action', '90 feet', 'Concentration, up to 1 hour', 'V', 'Add description here'),
('Identify', 'Divination', '1 Minute R', 'Touch', 'Instantaneous', 'V, S, M', 'Add description here'),
('Illusory Script', 'Illusion', '1 Minute R', 'Touch', '10 days', 'S, M', 'Add description here'),
('Inflict Wounds', 'Necromancy', '1 Action', 'Touch', 'Instantaneous', 'V, S', 'Add description here'),
('Jims Magic Missile', 'Evocation', '1 Action', '120 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Jump', 'Transmutation', '1 Action', 'Touch', '1 minute', 'V, S, M', 'Add description here'),
('Longstrider', 'Transmutation', '1 Action', 'Touch', '1 hour', 'V, S, M', 'Add description here'),
('Mage Armor', 'Abjuration', '1 Action', 'Touch', '8 hours', 'V, S, M', 'Add description here'),
('Magic Missile', 'Evocation', '1 Action', '120 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Magnify Gravity', 'Transmutation DG', '1 Action', '60 feet', '1 round', 'V, S', 'Add description here'),
('Protection from Evil and Good', 'Abjuration', '1 Action', 'Touch', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Puppet (UA)', 'Enchantment', '1 Action', '120 feet', 'Instantaneous', 'V', 'Add description here'),
('Purify Food and Drink', 'Transmutation', '1 Action R', '10 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Ray of Sickness', 'Necromancy', '1 Action', '60 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Remote Access (UA)', 'Transmutation T', '1 Action', '120 feet', '10 minutes', 'V, S', 'Add description here'),
('Sanctuary', 'Abjuration', '1 Bonus Action', '30 feet', '1 minute', 'V, S, M', 'Add description here'),
('Searing Smite', 'Evocation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Sense Emotion (UA)', 'Divination', '1 Action', 'Self', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Shield', 'Abjuration', '1 Reaction', 'Self', '1 round', 'V, S', 'Add description here'),
('Shield of Faith', 'Abjuration', '1 Bonus Action', '60 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Silent Image', 'Illusion', '1 Action', '60 feet', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Silvery Barbs', 'Enchantment', '1 Reaction', '60 feet', 'Instantaneous', 'V', 'Add description here'),
('Sleep', 'Enchantment', '1 Action', '90 feet', '1 minute', 'V, S, M', 'Add description here'),
('Snare', 'Abjuration', '1 Minute', 'Touch', 'Until dispelled or triggered', 'V, S, M', 'Add description here'),
('Speak with Animals', 'Divination', '1 Action R', 'Self', '10 minutes', 'V, S', 'Add description here'),
('Sudden Awakening (UA)', 'Enchantment', '1 Bonus Action', '10 feet', 'Instantaneous', 'V', 'Add description here'),
('Tashas Caustic Brew', 'Evocation', '1 Action', 'Self (30-foot line)', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Tashas Hideous Laughter', 'Enchantment', '1 Action', '30 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Tensers Floating Disk', 'Conjuration', '1 Action R', '30 feet', '1 hour', 'V, S, M', 'Add description here'),
('Thunderous Smite', 'Evocation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Thunderwave', 'Evocation', '1 Action', 'Self (15-foot cube)', 'Instantaneous', 'V, S', 'Add description here'),
('Unearthly Chorus (UA)', 'Illusion', '1 Action', 'Self (30-foot radius)', 'Concentration, up to 10 minutes', 'V', 'Add description here'),
('Unseen Servant', 'Conjuration', '1 Action R', '60 feet', '1 hour', 'V, S, M', 'Add description here'),
('Wild Cunning (UA)', 'Transmutation', '1 Action R', '120 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Witch Bolt', 'Evocation', '1 Action', '30 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Wrathful Smite', 'Evocation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Zephyr Strike', 'Transmutation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Aganazzars Scorcher', 'Evocation', '1 Action', '30 Feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Aid', 'Abjuration', '1 Action', '30 Feet', '8 hours', 'V, S, M', 'Add description here'),
('Air Bubble', 'Conjuration', '1 Action', '60 Feet', '24 hours', 'S', 'Add description here'),
('Alter Self', 'Transmutation', '1 Action', 'Self', 'Concentration, up to 1 hour', 'V, S', 'Add description here'),
('Animal Messenger', 'Enchantment', '1 Action R', '30 Feet', '24 hours', 'V, S, M', 'Add description here'),
('Arcane Hacking (UA)', 'Transmutation T', '1 Action', 'Self', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Arcane Lock', 'Abjuration', '1 Action', 'Touch', 'Until dispelled', 'V, S, M', 'Add description here'),
('Augury', 'Divination', '1 Minute R', 'Self', 'Instantaneous', 'V, S, M', 'Add description here'),
('Barkskin', 'Transmutation', '1 Action', 'Touch', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Beast Sense', 'Divination', '1 Action R', 'Touch', 'Concentration, up to 1 hour', 'S', 'Add description here'),
('Blindness/Deafness', 'Necromancy', '1 Action', '30 Feet', '1 minute', 'V', 'Add description here'),
('Blur', 'Illusion', '1 Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Borrowed Knowledge', 'Divination', '1 Action', 'Self', '1 hour', 'V, S, M', 'Add description here'),
('Branding Smite', 'Evocation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Calm Emotions', 'Enchantment', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Cloud of Daggers', 'Conjuration', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Continual Flame', 'Evocation', '1 Action', 'Touch', 'Until dispelled', 'V, S, M', 'Add description here'),
('Cordon of Arrows', 'Transmutation', '1 Action', '5 feet', '8 hours', 'V, S, M', 'Add description here'),
('Crown of Madness', 'Enchantment', '1 Action', '120 feet', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Darkness', 'Evocation', '1 Action', '60 feet', 'Concentration, up to 10 minutes', 'V, M', 'Add description here'),
('Darkvision', 'Transmutation', '1 Action', 'Touch', '8 hours', 'V, S, M', 'Add description here'),
('Detect Thoughts', 'Divination', '1 Action', 'Self', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Digital Phantom (UA)', 'Abjuration T', '1 Action', 'Self', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Dragons Breath', 'Transmutation', '1 Bonus Action', 'Touch', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Dust Devil', 'Conjuration', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Earthbind', 'Transmutation', '1 Action', '300 feet', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Enhance Ability', 'Transmutation', '1 Action', 'Touch', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Enlarge/Reduce', 'Transmutation', '1 Action', '30 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Enthrall', 'Enchantment', '1 Action', '60 feet', '1 minute', 'V, S', 'Add description here'),
('Find Steed', 'Conjuration', '10 Minutes', '30 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Find Traps', 'Divination', '1 Action', '120 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Find Vehicle (UA)', 'Conjuration T', '10 Minutes', '30 feet', '8 hours', 'V, S', 'Add description here'),
('Flame Blade', 'Evocation', '1 Bonus Action', 'Self', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Flaming Sphere', 'Conjuration', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Flock of Familiars', 'Conjuration', '1 Minute', 'Touch', 'Concentration, up to 1 hour', 'V, S', 'Add description here'),
('Fortunes Favor', 'Divination D', '1 Minute', '60 feet', '1 hour', 'V, S, M', 'Add description here'),
('Gentle Repose', 'Necromancy', '1 Action R', 'Touch', '10 days', 'V, S, M', 'Add description here'),
('Gift of Gab', 'Enchantment', 'Reaction', 'Self', 'Instantaneous', 'V, S, M', 'Add description here'),
('Gust of Wind', 'Evocation', '1 Action', 'Self (60-foot line)', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Healing Spirit', 'Conjuration', '1 Bonus Action', '60 feet', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Heat Metal', 'Transmutation', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Hold Person', 'Enchantment', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Icingdeaths Frost (UA)', 'Evocation', '1 Action', 'Self (15-foot cone)', 'Instantaneous', 'S, M', 'Add description here'),
('Immovable Object', 'Transmutation DG', '1 Action', 'Touch', '1 hour', 'V, S, M', 'Add description here'),
('Invisibility', 'Illusion', '1 Action', 'Touch', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Jims Glowing Coin', 'Enchantment', '1 Action', '60 feet', '1 minute', 'S, M', 'Add description here'),
('Kinetic Jaunt', 'Transmutation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'S', 'Add description here'),
('Knock', 'Transmutation', '1 Action', '60 feet', 'Instantaneous', 'V', 'Add description here'),
('Lesser Restoration', 'Abjuration', '1 Action', 'Touch', 'Instantaneous', 'V, S', 'Add description here'),
('Levitate', 'Transmutation', '1 Action', '60 feet', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Locate Animals or Plants', 'Divination', '1 Action R', 'Self', 'Instantaneous', 'V, S, M', 'Add description here'),
('Locate Object', 'Divination', '1 Action', 'Self', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Magic Mouth', 'Illusion', '1 Minute R', '30 feet', 'Until dispelled', 'V, S, M', 'Add description here'),
('Magic Weapon', 'Transmutation', '1 Bonus Action', 'Touch', 'Concentration, up to 1 hour', 'V, S', 'Add description here'),
('Maximillians Earthen Grasp', 'Transmutation', '1 Action', '30 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Melfs Acid Arrow', 'Evocation', '1 Action', '90 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Mental Barrier (UA)', 'Abjuration', '1 Reaction', 'Self', '1 round', 'V', 'Add description here'),
('Mind Spike', 'Divination', '1 Action', '60 feet', 'Concentration, up to 1 hour', 'S', 'Add description here'),
('Mind Thrust (UA)', 'Enchantment', '1 Bonus Action', '60 feet', '1 round', 'V, S', 'Add description here'),
('Mirror Image', 'Illusion', '1 Action', 'Self', '1 minute', 'V, S', 'Add description here'),
('Misty Step', 'Conjuration', '1 Bonus Action', 'Self', 'Instantaneous', 'V', 'Add description here'),
('Moonbeam', 'Evocation', '1 Action', '120 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Nathairs Mischief', 'Illusion', '1 Action', '60ft', 'Concentration, up to 1 minute', 'S, M', 'Add description here'),
('Nathairs Mischief (UA)', 'Illusion', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'S, M', 'Add description here'),
('Nystuls Magic Aura', 'Illusion', '1 Action', 'Touch', '24 hours', 'V, S, M', 'Add description here'),
('Pass Without Trace', 'Abjuration', '1 Action', 'Self', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Phantasmal Force', 'Illusion', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Prayer of Healing', 'Evocation', '10 Minutes', '30 feet', 'Instantaneous', 'V', 'Add description here'),
('Protection from Poison', 'Abjuration', '1 Action', 'Touch', '1 hour', 'V, S', 'Add description here'),
('Pyrotechnics', 'Transmutation', '1 Action', '60 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Ray of Enfeeblement', 'Necromancy', '1 Action', '60 feet', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Rimes Binding Ice', 'Evocation', '1 Action', 'Self (30-foot cone)', 'Instantaneous', 'S, M', 'Add description here'),
('Rope Trick', 'Transmutation', '1 Action', 'Touch', '1 hour', 'V, S, M', 'Add description here'),
('Scorching Ray', 'Evocation', '1 Action', '120 feet', 'Instantaneous', 'V, S', 'Add description here'),
('See Invisibility', 'Divination', '1 Action', 'Self', '1 hour', 'V, S, M', 'Add description here'),
('Shadow Blade', 'Illusion', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Shatter', 'Evocation', '1 Action', '60 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Silence', 'Illusion', '1 Action R', '120 feet', 'Concentration, up to 10 minutes', 'V, S', 'Add description here'),
('Skywrite', 'Transmutation', '1 Action R', 'Sight', 'Concentration, up to 1 day', 'V, S', 'Add description here'),
('Snillocs Snowball Storm', 'Evocation', '1 Action', '90 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Spider Climb', 'Transmutation', '1 Action', 'Touch', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Spike Growth', 'Transmutation', '1 Action', '150 feet', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Spiritual Weapon', 'Evocation', '1 Bonus Action', '60 feet', '1 minute', 'V, S', 'Add description here'),
('Spray Of Cards', 'Conjuration', '1 Action', 'Self (15-foot cone)', 'Instantaneous', 'V, S, M', 'Add description here'),
('Spray of Cards (UA)', 'Conjuration', '1 Action', '15-foot cone', 'Instantaneous', 'V, S, M', 'Add description here'),
('Suggestion', 'Enchantment', '1 Action', '30 feet', 'Concentration, up to 8 hours', 'V, M', 'Add description here'),
('Summon Beast', 'Conjuration', '1 Action', '90 feet', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Tashas Mind Whip', 'Enchantment', '1 Action', '90 feet', '1 round', 'V', 'Add description here'),
('Thought Shield (UA)', 'Abjuration', '1 Action', 'Touch', '8 hours', 'V, S', 'Add description here'),
('Vortex Warp', 'Conjuration', '1 Action', '90 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Warding Bond', 'Abjuration', '1 Action', 'Touch', '1 hour', 'V, S, M', 'Add description here'),
('Warding Wind', 'Evocation', '1 Action', 'Self', 'Concentration, up to 10 minutes', 'V', 'Add description here'),
('Warp Sense', 'Divination', '1 Action', 'Self', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Web', 'Conjuration', '1 Action', '60 feet', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Wither and Bloom', 'Necromancy', '1 Action', '60 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Wristpocket', 'Conjuration D', '1 Action R', 'Self', 'Concentration, up to 1 hour', 'S', 'Add description here'),
('Zone of Truth', 'Enchantment', '1 Action', '60 feet', '10 minutes', 'V, S', 'Add description here'),
('Animate Dead', 'Necromancy', '1 Minute', '10 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Antagonize', 'Enchantment', '1 Action', '30 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Antagonize (UA)', 'Enchantment', '1 Action', '30 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Ashardalons Stride', 'Transmutation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V,S', 'Add description here'),
('Aura of Vitality', 'Evocation', '1 Action', 'Self (30-foot radius)', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Beacon of Hope', 'Abjuration', '1 Action', '30 feet', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Bestow Curse', 'Necromancy', '1 Action', 'Touch', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Blinding Smite', 'Evocation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Blink', 'Transmutation', '1 Action', 'Self', '1 minute', 'V, S', 'Add description here'),
('Call Lightning', 'Conjuration', '1 Action', '120 feet', 'Concentration, up to 10 minutes', 'V, S', 'Add description here'),
('Catnap', 'Enchantment', '1 Action', '30 feet', '10 minutes', 'S, M', 'Add description here'),
('Clairvoyance', 'Divination', '10 Minutes', '1 mile', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Conjure Animals', 'Conjuration', '1 Action', '60 feet', 'Concentration, up to 1 hour', 'V, S', 'Add description here'),
('Conjure Barrage', 'Conjuration', '1 Action', 'Self (60-foot cone)', 'Instantaneous', 'V, S, M', 'Add description here'),
('Conjure Lesser Demon (UA)', 'Conjuration', '1 Action', '60 feet', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Counterspell', 'Abjuration', '1 Reaction', '60 feet', 'Instantaneous', 'S', 'Add description here'),
('Create Food and Water', 'Conjuration', '1 Action', '30 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Crusaders Mantle', 'Evocation', '1 Action', 'Self', 'Concentration, up to 1 minute', 'V', 'Add description here'),
('Daylight', 'Evocation', '1 Action', '60 feet', '1 hour', 'V, S', 'Add description here'),
('Dispel Magic', 'Abjuration', '1 Action', '120 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Elemental Weapon', 'Transmutation', '1 Action', 'Touch', 'Concentration, up to 1 hour', 'V, S', 'Add description here'),
('Enemies Abound', 'Enchantment', '1 Action', '120 feet', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Erupting Earth', 'Transmutation', '1 Action', '120 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Fast Friends', 'Enchantment', '1 Action', '30 feet', 'Concentration, up to 1 hour', 'V', 'Add description here'),
('Fear', 'Illusion', '1 Action', 'Self (30-foot cone)', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Feign Death', 'Necromancy', '1 Action R', 'Touch', '1 hour', 'V, S, M', 'Add description here'),
('Fireball', 'Evocation', '1 Action', '150 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Flame Arrows', 'Transmutation', '1 Action', 'Touch', 'Concentration, up to 1 hour', 'V, S', 'Add description here'),
('Flame Stride (UA)', 'Transmutation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Fly', 'Transmutation', '1 Action', 'Touch', 'Concentration, up to 10 minute', 'V, S, M', 'Add description here'),
('Freedom of the Waves (HB)', 'Conjuration HB', '1 action', '120 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Galders Tower', 'Conjuration', '10 Minutes', '30 feet', '24 hours', 'V, S, M', 'Add description here'),
('Gaseous Form', 'Transmutation', '1 Action', 'Touch', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Glyph of Warding', 'Abjuration', '1 Hour', 'Touch', 'Until dispelled or triggered', 'V, S, M', 'Add description here'),
('Haste', 'Transmutation', '1 Action', '30 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Haywire (UA)', 'Enchantment T', '1 Action', '90 feet', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('House of Cards (UA)', 'Conjuration', '1 Minute', 'Touch', '24 hours', 'V, S, M', 'Add description here'),
('Hunger Of Hadar', 'Conjuration', '1 Action', '150 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Hypnotic Pattern', 'Illusion', '1 Action', '120 feet', 'Concentration, up to 1 minute', 'S, M', 'Add description here'),
('Incite Greed', 'Enchantment', '1 action', '30 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Intellect Fortress', 'Abjuration', '1 Action', '30 feet', 'Concentration, up to 1 hour', 'V', 'Add description here'),
('Invisibility To Cameras (UA)', 'Illusion T', '1 Action', '10 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Leomunds Tiny Hut', 'Evocation', '1 Minute R', 'Self (10-foot radius hemisphere)', '8 hours', 'V, S, M', 'Add description here'),
('Life Transference', 'Necromancy', '1 Action', '30 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Lightning Arrow', 'Transmutation', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Lightning Bolt', 'Evocation', '1 Action', 'Self (100-foot line)', 'Instantaneous', 'V, S, M', 'Add description here'),
('Magic Circle', 'Abjuration', '1 Minute', '10 feet', '1 hour', 'V, S, M', 'Add description here'),
('Major Image', 'Illusion', '1 Action', '120 feet', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Mass Healing Word', 'Evocation', '1 Bonus Action', '60 feet', 'Instantaneous', 'V', 'Add description here'),
('Meld into Stone', 'Transmutation', '1 Action R', 'Touch', '8 hours', 'V, S', 'Add description here'),
('Melfs Minute Meteors', 'Evocation', 'Self', '120 feet', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Motivational Speech', 'Enchantment', '1 hour', '60 feet', '1 hour', 'V', 'Add description here'),
('Nondetection', 'Abjuration', '1 Action', 'Touch', '8 hours', 'V, S, M', 'Add description here'),
('Phantom Steed', 'Illusion', '1 Minute R', '30 feet', '1 hour', 'V, S', 'Add description here'),
('Plant Growth', 'Transmutation', '1 Action or 8 Hours', '150 feet', 'Instantaneous', 'V, S', 'Add description here'),
('Protection from Ballistics (UA)', 'Abjuration T', '1 Action', 'Touch', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Protection from Energy', 'Abjuration', '1 Action', 'Touch', 'Concentration, up to 1 hour', 'V, S', 'Add description here'),
('Psionic Blast (UA)', 'Evocation', '1 Action', 'Self (30-foot cone)', 'Instantaneous', 'V', 'Add description here'),
('Pulse Wave', 'Evocation D', '1 Action', 'Self (30-foot cone)', 'Instantaneous', 'V, S', 'Add description here'),
('Remove Curse', 'Abjuration', '1 Action', 'Touch', 'Instantaneous', 'V, S', 'Add description here'),
('Revivify', 'Necromancy', '1 Action', 'Touch', 'Instantaneous', 'V, S, M', 'Add description here'),
('Sending', 'Evocation', '1 Action', 'Unlimited', '1 round', 'V, S, M', 'Add description here'),
('Sleet Storm', 'Conjuration', '1 Action', '120 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Slow', 'Transmutation', '1 Action', '120 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Speak with Dead', 'Necromancy', '1 Action', '10 feet', '10 minutes', 'V, S, M', 'Add description here'),
('Speak with Plants', 'Transmutation', '1 Action', 'Self (30-foot radius)', '10 minutes', 'V, S', 'Add description here'),
('Spirit Guardians', 'Conjuration', '1 Action', 'Self (15-foot radius)', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Spirit Shroud', 'Necromancy', '1 Bonus Action', 'Self', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Stinking Cloud', 'Conjuration', '1 Action', '90 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here'),
('Summon Fey', 'Conjuration', '1 Action', '90 feet', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Summon Lesser Demons', 'Conjuration', '1 Action', '60 Feet', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Summon Shadowspawn', 'Conjuration', '1 Action', '90 feet', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Summon Undead', 'Necromancy', '1 Action', '90 feet', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Summon Warrior Spirit (UA)', 'Conjuration', '1 Action', '90 feet', 'Concentration, up to 1 hour', 'V, S, M', 'Add description here'),
('Thunder Step', 'Conjuration', '1 Action', '90 feet', 'Instantaneous', 'V', 'Add description here'),
('Tidal Wave', 'Conjuration', '1 Action', '120 feet', 'Instantaneous', 'V, S, M', 'Add description here'),
('Tiny Servant', 'Transmutation', '1 Minute', 'Touch', '8 hours', 'V, S', 'Add description here'),
('Tongues', 'Divination', '1 Action', 'Touch', '1 hour', 'V, M', 'Add description here'),
('Vampiric Touch', 'Necromancy', '1 Action', 'Self', 'Concentration, up to 1 minute', 'V, S', 'Add description here'),
('Wall of Sand', 'Evocation', '1 Action', '90 feet', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Wall of Water', 'Evocation', '1 Action', '60 feet', 'Concentration, up to 10 minutes', 'V, S, M', 'Add description here'),
('Water Breathing', 'Transmutation', '1 Action R', '30 feet', '24 hours', 'V, S, M', 'Add description here'),
('Water Walk', 'Transmutation', '1 Action R', '30 feet', '1 hour', 'V, S, M', 'Add description here'),
('Wind Wall', 'Evocation', '1 Action', '120 feet', 'Concentration, up to 1 minute', 'V, S, M', 'Add description here');